name = "jpcal"
main = "src/index.ts"
compatibility_date = "2024-10-31"

# compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true
head_sampling_rate = 1

[triggers]
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "holiday-jp"
database_id = "affcf761-fc16-4637-a84f-a0c90ff515ee"
migrations_dir = "drizzle"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
